import { JAVASCRIPT_CODE } from './scripts';
import { CSS_STYLES } from './styles';

export interface BaseTemplateData {
  sessionName: string;
  projectsList: string[];
  statusClass: string;
  totalIssues: number;
  critical: number;
  high: number;
  medium: number;
  low: number;
  filtersSection: string;
  directoriesSection: string;
}

export function generateBaseTemplate(data: BaseTemplateData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline';">
  <title>QualOps Report - ${data.sessionName}</title>
  <style>
    ${CSS_STYLES}
  </style>
</head>
<body>
  <div class="container">
    <main class="main-content">
      <header id="overview" class="page-header" style="background: white; border: 1px solid var(--color-border); border-radius: 6px; padding: 20px; margin-bottom: 24px;">
        <div style="display: flex; justify-content: space-between; align-items: flex-start;">
          <div>
            <h1 style="font-size: 24px; font-weight: 600; margin: 0 0 8px 0; color: var(--color-text);">${data.sessionName}</h1>
            <div style="font-size: 14px; color: var(--color-text-secondary); margin-bottom: 16px;">
              ${data.projectsList.join(', ')}
            </div>
            <div style="font-size: 14px; line-height: 1.8; color: var(--color-text);">
              <div style="margin-bottom: 4px;"><strong>Judgment:</strong> <span style="color: ${data.statusClass === 'passed' ? 'var(--color-success)' : 'var(--color-danger)'};">${data.statusClass === 'passed' ? 'PASSED' : 'FAILED'}</span></div>
              <div>Total Issues: ${data.totalIssues}</div>
              <div>Critical: ${data.critical}</div>
              <div>High: ${data.high}</div>
              <div>Medium: ${data.medium}</div>
              <div>Low: ${data.low}</div>
            </div>
          </div>
          <div style="text-align: right; font-size: 13px; color: var(--color-text-secondary);">
            <div>Generated: ${new Date().toLocaleDateString()}</div>
            <div>${new Date().toLocaleTimeString()}</div>
          </div>
        </div>
      </header>

      <section id="files">
        ${data.filtersSection}
        ${data.directoriesSection}
      </section>

      <footer style="margin-top: 20px; padding-top: 12px; border-top: 1px solid var(--color-border); text-align: center; color: var(--color-text-secondary); font-size: 11px;">
        Generated by QualOps Pipeline | Session: ${data.sessionName}
      </footer>
    </main>
  </div>

  <script>
    ${JAVASCRIPT_CODE}
  </script>
</body>
</html>`;
}
